// src/utils/finance/index.ts
export { getSaldoAtual } from './getSaldoAtual.js'
export { getSaldoFuturo } from './getSaldoFuturo.js'
export { getTotaisMensais } from './getTotaisMensais.js'
export { getComparativoMensal } from './getComparativoMensal.js'
export { getGastosPorCategoria } from './getGastosPorCategoria.js'
export { getGastosPorCartao } from './getGastosPorCartao.js'
export { getTopCategoriasGasto } from './getTopCategoriasGasto.js'
export { getCartoesEstourados } from './getCartoesEstourados.js'
export { getCartoesAVencer } from './getCartoesAVencer.js'
export { getParcelasPendentes } from './getParcelasPendentes.js'
export { getResumoAnual } from './getResumoAnual.js'
export { getReceitasDoMes } from './getReceitasDoMes.js'
export { getDespesasDoMes } from './getDespesasDoMes.js'
export { saveExpenseHistory } from './saveExpenseHistory.js'

// Re-export types from their respective files
export type { GastosPorCategoriaResult } from './getGastosPorCategoria.js'
export type { GastosPorCartaoResult } from './getGastosPorCartao.js'
export type { TopCategoriasResult } from './getTopCategoriasGasto.js'
export type { CartoesEstouradosResult } from './getCartoesEstourados.js'
export type { CartoesAVencerResult } from './getCartoesAVencer.js'
export type { ParcelasPendentesResult } from './getParcelasPendentes.js'
export type { ResumoAnualResult } from './getResumoAnual.js'
export type { ReceitasDoMesResult } from './getReceitasDoMes.js'
export type { DespesasDoMesResult } from './getDespesasDoMes.js'